import { mysqlTable, mysqlSchema, AnyMySqlColumn, primaryKey, varchar, text, int, bigint, index, tinyint } from "drizzle-orm/mysql-core"
import { sql } from "drizzle-orm"

export const abreviationTable = mysqlTable("abreviation_table", {
	originalLanguage: varchar("original_language", { length: 70 }).notNull(),
	languageCode: varchar("language_code", { length: 16 }),
},
(table) => [
	primaryKey({ columns: [table.originalLanguage], name: "abreviation_table_original_language"}),
]);

export const anotherJoinTable = mysqlTable("another_join_table", {
	imdbId: text("imdb_id"),
	primaryTitle: text(),
	isAdult: tinyint(),
	startYear: int(),
	runtimeMinutes: int(),
	revenue: bigint({ mode: "number" }),
	budget: bigint({ mode: "number" }),
	nconst: text(),
	category: text(),
	action: text("Action"),
	scienceFiction: text("Science_Fiction"),
	adventure: text("Adventure"),
	drama: text("Drama"),
	crime: text("Crime"),
	thriller: text("Thriller"),
	fantasy: text("Fantasy"),
	comedy: text("Comedy"),
	romance: text("Romance"),
	western: text("Western"),
	mystery: text("Mystery"),
	war: text("War"),
	animation: text("Animation"),
	family: text("Family"),
	horror: text("Horror"),
	music: text("Music"),
	history: text("History"),
	tvMovie: text("TV_Movie"),
	documentary: text("Documentary"),
});

export const filterJoinTable = mysqlTable("filter_join_table", {
	imdbId: text("imdb_id"),
	primaryTitle: text(),
	isAdult: tinyint(),
	startYear: int(),
	runtimeMinutes: int(),
	revenue: bigint({ mode: "number" }),
	budget: bigint({ mode: "number" }),
	nconst: text(),
	category: text(),
	primaryName: text(),
	birthYear: int(),
	action: text("Action"),
	scienceFiction: text("Science_Fiction"),
	adventure: text("Adventure"),
	drama: text("Drama"),
	crime: text("Crime"),
	thriller: text("Thriller"),
	fantasy: text("Fantasy"),
	comedy: text("Comedy"),
	romance: text("Romance"),
	western: text("Western"),
	mystery: text("Mystery"),
	war: text("War"),
	animation: text("Animation"),
	family: text("Family"),
	horror: text("Horror"),
	music: text("Music"),
	history: text("History"),
	tvMovie: text("TV_Movie"),
	documentary: text("Documentary"),
});

export const genreTable = mysqlTable("genre_table", {
	id: int().notNull(),
	action: text("Action"),
	scienceFiction: text("Science_Fiction"),
	adventure: text("Adventure"),
	drama: text("Drama"),
	crime: text("Crime"),
	thriller: text("Thriller"),
	fantasy: text("Fantasy"),
	comedy: text("Comedy"),
	romance: text("Romance"),
	western: text("Western"),
	mystery: text("Mystery"),
	war: text("War"),
	animation: text("Animation"),
	family: text("Family"),
	horror: text("Horror"),
	music: text("Music"),
	history: text("History"),
	tvMovie: text("TV_Movie"),
	documentary: text("Documentary"),
},
(table) => [
	primaryKey({ columns: [table.id], name: "genre_table_id"}),
]);

export const joinTable = mysqlTable("join_table", {
	imdbId: text("imdb_id"),
	primaryTitle: text(),
	isAdult: tinyint(),
	startYear: int(),
	runtimeMinutes: int(),
	revenue: bigint({ mode: "number" }),
	budget: bigint({ mode: "number" }),
	action: text("Action"),
	scienceFiction: text("Science_Fiction"),
	adventure: text("Adventure"),
	drama: text("Drama"),
	crime: text("Crime"),
	thriller: text("Thriller"),
	fantasy: text("Fantasy"),
	comedy: text("Comedy"),
	romance: text("Romance"),
	western: text("Western"),
	mystery: text("Mystery"),
	war: text("War"),
	animation: text("Animation"),
	family: text("Family"),
	horror: text("Horror"),
	music: text("Music"),
	history: text("History"),
	tvMovie: text("TV_Movie"),
	documentary: text("Documentary"),
});

export const mainTable = mysqlTable("main_table", {
	id: int().notNull(),
	title: varchar({ length: 512 }),
	voteAverage: text("vote_average"),
	voteCount: text("vote_count"),
	status: text(),
	releaseDate: text("release_date"),
	revenue: bigint({ mode: "number" }),
	runtime: int(),
	adult: tinyint(),
	backdropPath: text("backdrop_path"),
	budget: bigint({ mode: "number" }),
	homepage: text(),
	imdbId: text("imdb_id"),
	languageCode: text("language_code"),
	originalTitle: text("original_title"),
	overview: text(),
	popularity: text(),
	posterPath: text("poster_path"),
	tagline: text(),
	productionCompanies: text("production_companies"),
	productionCountries: text("production_countries"),
	spokenLanguages: text("spoken_languages"),
	keywords: text(),
},
(table) => [
	index("title_index").on(table.title),
	primaryKey({ columns: [table.id], name: "main_table_id"}),
]);

export const nameBasics = mysqlTable("name_basics", {
	nconst: varchar({ length: 300 }).notNull(),
	primaryName: text(),
	birthYear: int(),
	deathYear: int(),
	primaryProfession: text(),
	knownForTitles: text(),
},
(table) => [
	primaryKey({ columns: [table.nconst], name: "name_basics_nconst"}),
]);

export const titleBasics = mysqlTable("title_basics", {
	imdbId: varchar("imdb_id", { length: 300 }).notNull(),
	titleType: text(),
	primaryTitle: text(),
	originalTitle: text(),
	isAdult: tinyint(),
	startYear: int(),
	endYear: int(),
	runtimeMinutes: int(),
	genres: text(),
},
(table) => [
	primaryKey({ columns: [table.imdbId], name: "title_basics_imdb_id"}),
]);

export const titleCrew = mysqlTable("title_crew", {
	imdbId: varchar("imdb_id", { length: 300 }).notNull(),
	directors: text(),
	writers: text(),
},
(table) => [
	primaryKey({ columns: [table.imdbId], name: "title_crew_imdb_id"}),
]);

export const titlePrincipals = mysqlTable("title_principals", {
	imdbId: varchar("imdb_id", { length: 300 }),
	ordering: int(),
	nconst: text(),
	category: text(),
	job: text(),
	characters: text(),
});

export const totalJoinTable = mysqlTable("total_join_table", {
	imdbId: text("imdb_id"),
	primaryTitle: text(),
	isAdult: tinyint(),
	startYear: int(),
	runtimeMinutes: int(),
	revenue: bigint({ mode: "number" }),
	budget: bigint({ mode: "number" }),
	nconst: text(),
	category: text(),
	primaryName: text(),
	birthYear: int(),
	action: text("Action"),
	scienceFiction: text("Science_Fiction"),
	adventure: text("Adventure"),
	drama: text("Drama"),
	crime: text("Crime"),
	thriller: text("Thriller"),
	fantasy: text("Fantasy"),
	comedy: text("Comedy"),
	romance: text("Romance"),
	western: text("Western"),
	mystery: text("Mystery"),
	war: text("War"),
	animation: text("Animation"),
	family: text("Family"),
	horror: text("Horror"),
	music: text("Music"),
	history: text("History"),
	tvMovie: text("TV_Movie"),
	documentary: text("Documentary"),
});
